# .github/workflows/caller-workflow.yml
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "alpine1"
            context: "./alpine1"
            dockerfile_path: "./alpine1/Dockerfile"
            repository: "trial451ad8.jfrog.io/dev-docker-docker/alpine1"
            image_tag: "alpine1-${{ github.run_id }}"

    uses: girichinna27/gh-worker/.github/workflows/worker-workflow.yml@main
    with:
      image_name: ${{ matrix.name }}
      context: ${{ matrix.context }}
      dockerfile_path: ${{ matrix.dockerfile_path }}
      image_tag: ${{ matrix.image_tag }}
      registry: 'trial451ad8.jfrog.io'
      org: "ortseam"
      application_tags: "v1.0"
      artifactory_url: ${{ matrix.repository }}

    secrets:
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
      SSD_TEAM_TOKEN: ${{ secrets.SSD_TEAM_TOKEN }}      
