# .github/workflows/caller-workflow.yml
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "alpine3"
            context: "./alpine3"
            dockerfile_path: "./alpine1/Dockerfile"
            repository: "trial451ad8.jfrog.io/dev-docker-docker/alpinei3"
            image_tag: "${{ github.run_number }}"

          - name: "alpine4"
            context: "./alpine4"
            dockerfile_path: "./alpine2/Dockerfile"
            repository: "trial451ad8.jfrog.io/dev-docker-docker/alpine4"
            image_tag: "${{ github.run_number }}"

    uses: girichinna27/gh-worker/.github/workflows/worker-workflow.yml@main
    with:
      image_name: ${{ matrix.name }}
      context: ${{ matrix.context }}
      dockerfile_path: ${{ matrix.dockerfile_path }}
      image_tag: ${{ matrix.image_tag }}
      registry: 'trial451ad8.jfrog.io'
      org: "ortseam"
      application_tags: "v1.0"
      artifactory_url: ${{ matrix.repository }}

    secrets:
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
